import type { ToolDef } from "@/db/schema";

type Seed = {
  slug: string;
  name: string;
  publisher: string;
  version: string;
  description: string;
  category: string;
  executor: string;
  builtin?: boolean;
  verified?: boolean;
  tools: [string, string, 1 | 2 | 3 | 4][];
  canDo: string[];
  cannotDo: string[];
  dataAccess: string[];
  permissions: string[];
  oauthScopes?: string[];
  networkDestinations: string[];
  retention: string;
};

function toTools(t: Seed["tools"]): ToolDef[] {
  return t.map(([name, description, level]) => ({
    name,
    description,
    level,
    confirmation: level === 4 ? "step_up" : level === 3 ? "required" : "none",
  }));
}

const SEEDS: Seed[] = [
  {
    slug: "android.core",
    name: "Android Body",
    publisher: "AI Phone",
    version: "1.4.0",
    description: "Native contacts, maps navigation, reminders and camera — performed through Android APIs, never screen-scraping.",
    category: "Device",
    executor: "android",
    builtin: true,
    tools: [
      ["read_contacts", "Look up a contact by name", 1],
      ["start_navigation", "Open turn-by-turn navigation via Maps intent", 2],
      ["create_reminder", "Create a time or geofence reminder", 2],
      ["open_camera", "Open the camera with an inspection template", 2],
    ],
    canDo: ["Look up approved contacts", "Start navigation to an address", "Create arrival reminders", "Open the camera"],
    cannotDo: ["Read message history", "Change system settings", "Install apps"],
    dataAccess: ["Contact names & numbers", "Approximate location (on arrival)"],
    permissions: ["android.contacts.read", "android.location.geofence", "android.camera"],
    networkDestinations: [],
    retention: "On-device only. Nothing is uploaded.",
  },
  {
    slug: "voice.telnyx",
    name: "Telnyx Voice",
    publisher: "AI Phone",
    version: "2.1.3",
    description: "Wi-Fi calling over Telnyx WebRTC with short-lived, device-scoped tokens and call-consent handling.",
    category: "Voice",
    executor: "voice",
    tools: [
      ["get_call_log", "Read recent call history", 1],
      ["place_call", "Place an outbound call from the assigned number", 3],
      ["send_sms", "Send a text message from the assigned number", 3],
    ],
    canDo: ["Place and receive Wi-Fi calls", "Show caller identification", "Read the call log"],
    cannotDo: ["Store master Telnyx credentials on the phone", "Record without consent", "Place emergency calls silently"],
    dataAccess: ["Dialed numbers", "Call duration", "Transcripts (with consent)"],
    permissions: ["audio.record", "network.telnyx", "bluetooth.headset"],
    oauthScopes: ["voice.device_token"],
    networkDestinations: ["sip.telnyx.com", "api.telnyx.com"],
    retention: "Call logs kept 90 days. Recordings only with explicit consent.",
  },
  {
    slug: "voice.twilio",
    name: "Twilio Voice",
    publisher: "AI Phone",
    version: "2.0.8",
    description: "Wi-Fi calling through the Twilio Voice mobile SDK with push-based incoming calls.",
    category: "Voice",
    executor: "voice",
    tools: [
      ["get_call_log", "Read recent call history", 1],
      ["place_call", "Place an outbound call from the assigned number", 3],
      ["send_sms", "Send a text message from the assigned number", 3],
    ],
    canDo: ["Place and receive Wi-Fi calls", "Receive calls after the app is terminated", "Read the call log"],
    cannotDo: ["Store master Twilio credentials on the phone", "Record without consent"],
    dataAccess: ["Dialed numbers", "Call duration"],
    permissions: ["audio.record", "network.twilio", "push.incoming_call"],
    oauthScopes: ["voice.access_token"],
    networkDestinations: ["voice-js.twilio.com", "api.twilio.com"],
    retention: "Call logs kept 90 days.",
  },
  {
    slug: "com.tyreeseburton.playwright.web-task",
    name: "Web Butler",
    publisher: "Tyreese Burton",
    version: "1.0.0",
    description: "Hosted Playwright browser worker. Operates sites without an API, with live session, screenshots and a full action log.",
    category: "Browser",
    executor: "playwright",
    tools: [
      ["capture_page", "Open an approved page and capture a screenshot", 1],
      ["fill_form", "Fill a web form without submitting it", 2],
      ["complete_web_task", "Submit a form or finish a web workflow", 3],
    ],
    canDo: ["Browse approved domains", "Fill forms without submitting", "Capture screenshots as evidence", "Quarantine downloads"],
    cannotDo: ["Enter passwords supplied by the model", "Visit unapproved domains", "Submit financial forms without confirmation"],
    dataAccess: ["Page content on approved domains", "Screenshots", "Final URL"],
    permissions: ["network.approved_domains", "browser.session"],
    networkDestinations: ["browser.aiphone.dev", "user-approved domains"],
    retention: "Screenshots and action log kept 30 days.",
  },
  {
    slug: "fleetos",
    name: "Fleet OS",
    publisher: "Fleet OS Inc.",
    version: "3.2.0",
    description: "Work orders, job sites and estimates from your Fleet OS account through its official MCP server.",
    category: "Field service",
    executor: "mcp",
    tools: [
      ["get_work_order", "Open a work order with customer and site", 1],
      ["draft_estimate", "Prepare an estimate from inspection notes and photos", 2],
      ["send_estimate", "Send an estimate to the customer", 3],
    ],
    canDo: ["Read assigned work orders", "Draft estimates", "Attach inspection photographs"],
    cannotDo: ["Send estimates without confirmation", "Change pricing rules", "Delete work orders"],
    dataAccess: ["Customer name & address", "Work order details", "Inspection photos"],
    permissions: ["mcp.fleetos.read", "mcp.fleetos.draft"],
    oauthScopes: ["workorders.read", "estimates.write"],
    networkDestinations: ["mcp.fleetos.com"],
    retention: "Nothing retained by the capability; Fleet OS retains per your contract.",
  },
  {
    slug: "google.workspace",
    name: "Google Workspace",
    publisher: "Google LLC",
    version: "1.7.2",
    description: "Gmail and Google Calendar as typed capabilities with scoped OAuth.",
    category: "Productivity",
    executor: "api",
    tools: [
      ["read_calendar", "Read upcoming events", 1],
      ["draft_email", "Write a Gmail draft", 2],
      ["send_email", "Send an email from Gmail", 3],
      ["create_event", "Schedule a calendar event", 3],
    ],
    canDo: ["Read upcoming events", "Draft email", "Schedule events after confirmation"],
    cannotDo: ["Delete mail", "Change sharing settings", "Send without confirmation"],
    dataAccess: ["Event titles & times", "Email drafts"],
    permissions: ["oauth.google"],
    oauthScopes: ["gmail.compose", "calendar.events"],
    networkDestinations: ["gmail.googleapis.com", "www.googleapis.com"],
    retention: "Not retained.",
  },
  {
    slug: "microsoft.365",
    name: "Microsoft 365",
    publisher: "Microsoft",
    version: "1.3.0",
    description: "Outlook mail and calendar through Microsoft Graph with tenant-level consent.",
    category: "Productivity",
    executor: "api",
    tools: [
      ["read_calendar", "Read upcoming events", 1],
      ["draft_email", "Write an Outlook draft", 2],
      ["send_email", "Send an email from Outlook", 3],
    ],
    canDo: ["Read Outlook calendar", "Draft Outlook mail"],
    cannotDo: ["Delete items", "Modify tenant settings"],
    dataAccess: ["Event titles & times", "Email drafts"],
    permissions: ["oauth.microsoft"],
    oauthScopes: ["Mail.ReadWrite", "Calendars.Read"],
    networkDestinations: ["graph.microsoft.com"],
    retention: "Not retained.",
  },
  {
    slug: "quickbooks",
    name: "QuickBooks",
    publisher: "Intuit",
    version: "1.1.4",
    description: "Read customers, draft invoices, check invoice status. Refunds are restricted and always need step-up.",
    category: "Finance",
    executor: "api",
    tools: [
      ["read_customers", "Read approved customers", 1],
      ["draft_invoice", "Prepare an invoice draft", 2],
      ["send_invoice", "Send an invoice to a customer", 3],
      ["issue_refund", "Issue a refund", 4],
    ],
    canDo: ["Read approved customers", "Draft invoices", "Check invoice status"],
    cannotDo: ["Send invoices without confirmation", "Issue refunds silently", "Change bank information"],
    dataAccess: ["Customer name", "Invoice details", "Payment status"],
    permissions: ["oauth.quickbooks"],
    oauthScopes: ["com.intuit.quickbooks.accounting"],
    networkDestinations: ["quickbooks.api.intuit.com"],
    retention: "Not retained.",
  },
  {
    slug: "slack",
    name: "Slack",
    publisher: "Slack Technologies",
    version: "1.2.0",
    description: "Summarize channels and post messages on your behalf after confirmation.",
    category: "Communication",
    executor: "api",
    tools: [
      ["read_channels", "Summarize unread channels", 1],
      ["post_message", "Post a message to a channel", 3],
    ],
    canDo: ["Summarize unread channels", "Post messages after confirmation"],
    cannotDo: ["Delete messages", "Invite members"],
    dataAccess: ["Channel messages you can already read"],
    permissions: ["oauth.slack"],
    oauthScopes: ["channels:history", "chat:write"],
    networkDestinations: ["slack.com"],
    retention: "Not retained.",
  },
  {
    slug: "homeassistant",
    name: "Home Assistant",
    publisher: "Nabu Casa",
    version: "0.9.5",
    description: "Read sensor state and control doors and locks. Locks are Level 4 and need step-up.",
    category: "Smart home",
    executor: "mcp",
    tools: [
      ["read_state", "Read the state of a device or sensor", 1],
      ["unlock_door", "Unlock a door", 4],
    ],
    canDo: ["Read sensors", "Unlock doors with step-up authentication"],
    cannotDo: ["Disable alarms", "Modify automations"],
    dataAccess: ["Device state"],
    permissions: ["mcp.homeassistant"],
    oauthScopes: ["homeassistant.read", "homeassistant.lock"],
    networkDestinations: ["your-home.ui.nabu.casa"],
    retention: "Not retained.",
  },
  {
    slug: "spotify",
    name: "Spotify",
    publisher: "Spotify AB",
    version: "1.0.2",
    description: "Play music and playlists by voice.",
    category: "Media",
    executor: "api",
    tools: [["play_media", "Start playback on this phone", 2]],
    canDo: ["Play tracks and playlists"],
    cannotDo: ["Change account details", "Purchase subscriptions"],
    dataAccess: ["Playlists", "Playback state"],
    permissions: ["oauth.spotify"],
    oauthScopes: ["user-modify-playback-state"],
    networkDestinations: ["api.spotify.com"],
    retention: "Not retained.",
  },
  {
    slug: "twilio.admin",
    name: "Twilio Administration",
    publisher: "AI Phone",
    version: "0.8.0",
    description: "List and manage numbers assigned to your phones. Purchasing numbers spends money, so it is restricted.",
    category: "Voice",
    executor: "api",
    tools: [
      ["list_numbers", "List assigned numbers", 1],
      ["buy_number", "Purchase a new phone number", 4],
    ],
    canDo: ["List numbers", "Purchase numbers with step-up authentication"],
    cannotDo: ["Release numbers", "Change billing"],
    dataAccess: ["Phone numbers", "Usage totals"],
    permissions: ["oauth.twilio.admin"],
    oauthScopes: ["numbers.read", "numbers.purchase"],
    networkDestinations: ["api.twilio.com"],
    retention: "Not retained.",
  },
];

export const CATALOG_ROWS = SEEDS.map((s) => ({
  slug: s.slug,
  name: s.name,
  publisher: s.publisher,
  version: s.version,
  description: s.description,
  category: s.category,
  executor: s.executor,
  level: Math.max(...s.tools.map((t) => t[2])),
  verified: s.verified ?? true,
  signed: true,
  builtin: s.builtin ?? false,
  tools: toTools(s.tools),
  canDo: s.canDo,
  cannotDo: s.cannotDo,
  dataAccess: s.dataAccess,
  permissions: s.permissions,
  oauthScopes: s.oauthScopes ?? [],
  networkDestinations: s.networkDestinations,
  retention: s.retention,
}));
